# conda env create -f environment.yml
# you may have to run "conda config --set channel_priority false" before
name: cloudbandpy
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - cartopy>=0.21.1
  - netcdf4>=1.6.2
  - numpy>=1.23.5
  - pandas>=1.5.2
  - pyyaml>=6.0
  - scikit-image>=0.19.2
  - proj>=8.2
  - colorcet>=3.0.0
  - metpy>=1.4.0
