# Cloud band detection configuration file for North Pacific basin

# Compute the inheritance of each cloud band
run_inheritance_tracking: True

# Start/end date and time
startdate: "20160101.00"
enddate: "20161231.00"

# Domain
domain: "northPacific"
# Note: the northern border matters a lot: Polar regions has lots of cold clouds.
hemisphere: "north"
lon_west: 115
lon_east: 265
lat_north: 50
lat_south: -5

# Input files directory
clouddata_path: '/work/FAC/FGSE/IDYST/ddomeise/default/DATA/ERA5/netcdf/3hourly/surface_level/'
varname_infilename: 'top_net_thermal_radiation' # filename specific ("varname_year.nc")
resolution_data: 0.5 # degree
# Data specific
# calculate daily mean of the input variable for detection
qd_var: True
# temporal resolution of the input data
datatimeresolution: 3.0 # [hour]
# interval of detection in hours of wished period: 24h, 12h, 6h, 3h or 1h
period_detection: 24.
# needs conversion to W.m-2
olr_convert2wm2: True
# variable names in the input data
varname: 'ttr'
timecoord_name: 'time'
xcoord_name: 'longitude'
ycoord_name: 'latitude'

select_djfm: False

# Parameters file for cloud band detection
parameters_file: '/users/rpilon/codes/unil/CloudBandDetection/parameters/parameters_northhemisphere.yml'

# Save cloud bands, dates with cloud bands (in numpy or pickle formats)
saved_dirpath: './cloud_band_files' # directory where files will be saved

save_dailyvar: False # save daily mean of te variable
save_listcloudbands: True # list containing lists of cloud band (1 list per day)

# To load files saved in saved_dirpath and not load files containing raw data
load_saved_files: False


# Make figures
dir_figures: './cloud_band_figures'

fig_detection_process: False
fig_time_evolution_object: False
fig_time_evolution_var_cloudband: False
fig_overlay_cloudband: False
fig_show_bbox_around_blobs: False
fig_inheritance_tracking: False
fig_density: False